---
name: tweet_to_workflow
description: "Relay Tweets which mention #StackStormRocks to Slack"
enabled: true
trigger:
  type: twitter.matched_tweet
  parameters: {}
criteria: {}
action:
  ref: osdemo.osdemo1
  parameters:
    twitter_user: "{{trigger.user.screen_name}}"
    twitter_url: "{{trigger.url}}"
    remote_host: "localhost"
