---
name: twitter_to_slack
description: "Relay Tweets which mention #StackStormRocks to Slack"
enabled: true
trigger:
  type: twitter.matched_tweet
  parameters: {}
criteria: {}
action:
  ref: slack.post_message
  parameters:
    message: "Hey, We received a tweet from {{trigger.user.screen_name}}!\n {{trigger.url}}"
    channel: "#osdemo"
